version: "3.3"
services:
  ui:
    build: ./modules/ui
    image: ui
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./modules/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  api:
    build: ./modules/api
    image: api
    container_name: node
    ports:
      - 8084:8080
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data_mongo:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo
  redis-commander:
    image: tenstartups/redis-commander
    container_name: redis-commander
    command: --redis-host redis
    ports:
      - 8081:8081
    depends_on:
      - redis
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_portainer:/data
volumes:
  data_mongo:
  data_portainer:
