version: "3.3"
services:
  ui:
    build:
      context: ./modules/ui
      args:
        BASENAME: /
        JWT_STORAGE_KEY: access_token
    image: ui
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./modules/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - frontend
  api:
    build: ./modules/api
    image: api
    container_name: node
    ports:
      - 8084:8080
    environment:
      PORT: 8080
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: yolo
    depends_on:
      - mongo
      - redis
    networks:
      - frontend
      - backend
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data_mongo:/data/db
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo
    networks:
      - backend
      - tools
  redis-commander:
    image: tenstartups/redis-commander
    container_name: redis-commander
    command: --redis-host redis
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - backend
      - tools
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_portainer:/data
    networks:
      - tools
volumes:
  data_mongo:
  data_portainer:
networks:
  frontend:
  backend:
  tools:
