version: "3"
services:
  ui:
    build: ./modules/ui
    image: ui
    ports:
      - 8083:8080
    volumes:
      - dist:/opt/ui/dist
  api:
    build: ./modules/api
    image: api
    ports:
      - 8084:8080
    links:
      - mongo:mongo
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./modules/ui/nginx.conf:/etc/nginx/nginx.conf:ro
  mongo:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
  mongo-express:
    image: mongo-express
    links:
      - mongo:mongo
    ports:
      - 8082:8081
  redis-commander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - 8081:8081
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  dist:
