version: "3.3"
services:
  ui:
    build: ./modules/ui
    image: ui
    container_name: ui
    ports:
      - 8083:8080
    volumes:
      - dist:/opt/ui/dist
  api:
    build: ./modules/api
    image: api
    container_name: api
    ports:
      - 8084:8080
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./modules/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo
  redis-commander:
    image: tenstartups/redis-commander
    container_name: redis-commander
    command: --redis-host redis
    ports:
      - 8081:8081
    depends_on:
      - redis
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  dist:
  data:
