const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const FETCH_TODOS = 'FETCH_TODOS';

const PENDING = 'PENDING';
const FULFILLED = 'FULFILLED';
const REJECTED = 'REJECTED';

export const ActionTypes = {
  ADD_TODO,
  ADD_TODO_PENDING: `${ADD_TODO}_${PENDING}`,
  ADD_TODO_FULFILLED: `${ADD_TODO}_${FULFILLED}`,
  ADD_TODO_REJECTED: `${ADD_TODO}_${REJECTED}`,

  TOGGLE_TODO,
  TOGGLE_TODO_PENDING: `${TOGGLE_TODO}_${PENDING}`,
  TOGGLE_TODO_FULFILLED: `${TOGGLE_TODO}_${FULFILLED}`,
  TOGGLE_TODO_REJECTED: `${TOGGLE_TODO}_${REJECTED}`,

  FETCH_TODOS,
  FETCH_TODOS_PENDING: `${FETCH_TODOS}_${PENDING}`,
  FETCH_TODOS_FULFILLED: `${FETCH_TODOS}_${FULFILLED}`,
  FETCH_TODOS_REJECTED: `${FETCH_TODOS}_${REJECTED}`,
};
