/**
 * Action Types enum
 * @const
 */
export const ActionTypes = {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_TODOS_PENDING: 'FETCH_TODOS_PENDING',
  FETCH_TODOS_FULFILLED: 'FETCH_TODOS_FULFILLED',
  FETCH_TODOS_REJECTED: 'FETCH_TODOS_REJECTED',
};
